#!/usr/bin/env python3

import os
import click
import ekans.cmdline

@click.group()
def cli():
    pass


@click.command()
@click.option('--level', default="Bars()")
def play(level):
    ekans.cmdline.play(level=level)

@click.command()
@click.option('--name', default="RandomAIController")
@click.option('--seed')
@click.option('--level', default="Bars()")
@click.option("--headless/--no-headless", default=False)
def ai(name, headless, level, seed=None):
    ekans.cmdline.ai(name, headless=headless, seed=seed, level=level)

@click.command()
@click.option('--name', default="RandomAIController")
@click.option('--level', default="Bars()")
@click.option('--seed', default=1234)
@click.option('-n', default=30)
def score(name, n, seed, level):
    ekans.cmdline.score(name, n=n, seed=seed, level=level)

cli.add_command(play)
cli.add_command(ai)
cli.add_command(score)

cli()